# Site settings
name: Maisha Afroz
title: Maisha Afroz | Full Stack Dev
description: full stack developer 
url: "https://maishafroz.github.io/"
baseurl: ""
email: maishafroz@gmail.com
cover: https://maisha-afroz.github.io/img/og.png
logo: https://maisha-afroz.github.io/img/emojis/technologist.png
resume: https://maisha-afroz.github.io/resume.pdf
social:
  - title: email
    url: maishafroz@gmail.com
  - title: github
    url: https://github.com/maisha-afroz
  - title: linkedin
    url: https://www.linkedin.com/in/maishaafroz/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
